#!/bin/bash

# INPUT
# 0 Amber MDIN input file
# 1 Amber CRD file
# 2 Amber Topology file

# OUTPUT
# 0 Amber log file
# 1 Amber MDOUT file
# 2 Amber MDINFO file
# 3 Amber restart file

if [ "$1" == "-h" ]; then
	echo "	<application description=\"Amber\" script='amber' memory=\"7200\" ncpus=\"8\" walltime=\"72\">"
	echo "		<input index=\"0\" mimetype=\"chemical/x-amber-mdin\" description=\"Amber MDIN file\" filename=\"MDIN_{ID}.txt\" />";
	echo "		<input index=\"1\" mimetype=\"chemical/x-amber-crd\" description=\"CRD file\" filename=\"CRD_{ID}.crd\" />";
	echo "		<input index=\"2\" mimetype=\"chemical/x-amber-topology\" description=\"Amber Topology file\" filename=\"topology_{ID}.top\" />";

	echo "		<output index=\"0\" mimetype=\"chemical/x-amber-logfile\" description=\"Log file\" filename=\"logfile_{ID}.txt\" />";
	echo "		<output index=\"1\" mimetype=\"chemical/x-amber-mdout\" description=\"MDOUT file\" filename=\"MDOUT_{ID}.txt\" />";
	echo "		<output index=\"2\" mimetype=\"chemical/x-amber-mdinfo\" description=\"MDINFO file\" filename=\"MDINFO_{ID}.txt\" />";
	echo "		<output index=\"3\" mimetype=\"application/x-amber-crd\" description=\"Restart CRD file\" filename=\"restart_{ID}.crd\" />";
	echo "	</application>"
exit 0
fi



START_TIME=`date +%s`

echo "COMPLETED" > status

if [ "${HOME}" == "" ]; then
	export HOME=/tmp
fi;

export PATH=$PATH:/bin:/usr/bin

. /etc/profile.d/module.sh

module load amber
module load openbabel
module load intel-suite
module load java
module load mets-writer
module load mpi/intel-3.0.033


echo "Running Amber"
/bin/date


mpiexec pmemd -O -i input-0  -c input-1 \
	-ref input-1 -p input-2  

ln -s logfile output-0
ln -s mdout   output-1
ln -s mdinfo  output-2
ln -s restrt  output-3


END_TIME=`date +%s`

let "WALLTIME=${END_TIME}-${START_TIME}"

echo ${WALLTIME} > walltime
