<?php
#    $orcid_client_id = '0000-0001-7197-7095'; // this is your consumer key
#    $orcid_client_secret = '2801423d-88b0-4809-b6d8-87eede5ec00c'; // this is your secret
    $orcid_client_id = '0000-0003-1797-3186';
    $orcid_client_secret = '89837e74-ff5a-46a1-8690-4913538cf5e5';

#curl -i -L -k -H 'Accept: application/json' --data 'client_id=0000-0003-1797-3186&client_secret=89837e74-ff5a-46a1-8690-4913538cf5e5&grant_type=authorization_code&redirect_uri=https://portal.hpc.ic.ac.uk&code=REPLACE WITH OAUTH CODE' https://pub.orcid.org/oauth/token
?>
